name: Diff on Commit

on: 
  push:
    branches:
      - main

jobs:
  diff_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git fetch --all

    - name: Generate Diff
      id: generate_diff
      run: |
        # Sprawdź, czy jest poprzedni commit
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          DIFF_OUTPUT=$(git diff HEAD^ HEAD)
        else
          DIFF_OUTPUT="Brak poprzedniego commitu - brak różnic do wyświetlenia."
        fi
        echo "${DIFF_OUTPUT}" > diff.txt
        echo "::set-output name=diff::${DIFF_OUTPUT}"

    - name: Send Diff to Discord
      if: steps.generate_diff.outputs.diff != 'Brak poprzedniego commitu - brak różnic do wyświetlenia.'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        curl -H "Content-Type: application/json" -X POST \
        -d "{\"content\": \"\`\`\`${{ steps.generate_diff.outputs.diff }}\`\`\`\"}" \
        $DISCORD_WEBHOOK
